<?xml version="1.0" encoding="utf-8"?><Database Name="Gap" Class="GapDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Gap.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GapConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cita" Member="Cita">
    <Type Name="Cita">
      <Column Name="IdCita" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoCita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPaciente" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Paciente" Member="Paciente">
    <Type Name="Paciente">
      <Column Name="IdPaciente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoCita" Member="TipoCita">
    <Type Name="TipoCita">
      <Column Name="IdTipoCita" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TipoCita" Member="TipoCita1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>